# Generated by Django 4.0.1 on 2022-01-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(default='my Store', max_length=150)),
                ('category', models.CharField(
                    choices=[('tech', 'Tech'), ('food', 'Food'), ('clothes', 'Clothes'), ('shoes', 'Shoes'),
                             ('home', 'Home')], default='tech', max_length=120)),
                ('revenue', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
